# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  application:
    name: hexletCorrection
  jpa:
    properties:
      hibernate:
        id:
          optimizer:
            pooled:
              preferred: pooled-lo
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    initialization-mode: always
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/hexletCorrection}
    username: ${JDBC_DATABASE_USERNAME:localUser}
    password: ${JDBC_DATABASE_PASSWORD:pass}
logging:
  level:
    root: debug
    web: debug
    sql: debug
